global:
  scrape_interval: 15s
  evaluation_interval: 15s

rule_files:
  # - "first_rules.yml"
  # - "second_rules.yml"

scrape_configs:
  # Prometheus itself
  - job_name: 'prometheus'
    static_configs:
      - targets: ['localhost:9090']

  # Frontend metrics
  - job_name: 'frontend'
    static_configs:
      - targets: ['frontend:3000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Patient Agent metrics
  - job_name: 'patient_agent'
    static_configs:
      - targets: ['uagents-dev:8002']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Trial Agent metrics
  - job_name: 'trial_agent'
    static_configs:
      - targets: ['uagents-dev:8003']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # Matching Agent metrics
  - job_name: 'matching_agent'
    static_configs:
      - targets: ['uagents-dev:8004']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # MCP Server metrics
  - job_name: 'mcp_server'
    static_configs:
      - targets: ['uagents-dev:8005']
    metrics_path: '/metrics'
    scrape_interval: 15s

  # ICP Canister metrics (if available)
  - job_name: 'icp_canister'
    static_configs:
      - targets: ['dfx-local:8000']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # Redis metrics
  - job_name: 'redis'
    static_configs:
      - targets: ['redis:6379']
    metrics_path: '/metrics'
    scrape_interval: 30s

  # PostgreSQL metrics (if using postgres_exporter)
  - job_name: 'postgres'
    static_configs:
      - targets: ['postgres:5432']
    metrics_path: '/metrics'
    scrape_interval: 30s

# Alerting rules
alerting:
  alertmanagers:
    - static_configs:
        - targets:
          # - alertmanager:9093

# Recording rules
rule_files:
  - "recording_rules.yml"
